### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by bmleight** [wswoodruff/strangeluv-native#5]
I wasn't sure where to leave this feedback, so I figured I'd open an issue with my feedback on improving the readme.  In no particular order:

* [Getting started instructions](https://github.com/wswoodruff/strangeluv-native#getting-started): should just include the steps for renaming.  You want to do this every time you start a project, so it makes sense for it to be in there right along other install instructions.
* "Now inside your ios folder, rename all of the top-level files and folders to your project's name." I don't seem to have to do this.  What issue do you get when you don't?
* You already have a few recipes going, so it probably makes sense to make a recipes section...unless I missed it somehow.
* The deployment section could use some flushing out

**Comment by wswoodruff** [comment]
Thanks for the feedback @bmleight! Any other issues you run into, pls drop them in here. I'll keep this issue open for a bit

**Comment by wswoodruff** [comment]
Add a troubleshooting section to README

**Comment by wswoodruff** [comment]
Closing since I believe the current README addresses these changes. Will reopen if this isn't true
